n = input('Digite algo')
#print('O tipo primitivo desse valor é',type(n))
#print('É um número?', n.isnumeric())
#print('É uma letra?', n.isalpha())
#print('É alfanumérico?', n.isalnum())
#print('É maiúsculo?',n.isupper())
print(f'O tipo primitivo desse valor é {type(n)}')
print(f'É um número? {n.isnumeric()}')
print('É uma letra?{}'.format(n.isalpha()))
print(f'Está em maiúsculo?{n.isupper()}')
print(f'Está em minúsculo?{n.islower()}')
print('Está com letra capitular?{}'.format(n.istitle()))
print('É alfanumérico?',n.isalnum())